MyDBInstance:
  Type: AWS::RDS::DBInstance
  Properties:
    DBInstanceIdentifier: mydbinstance
    AllocatedStorage: 20
    DBInstanceClass: db.t3.micro
    Engine: mysql
    MasterUsername: admin
    MasterUserPassword: Password123!
    VPCSecurityGroups:
      - !Ref RDSSecurityGroup
    DBSubnetGroupName: !Ref DBSubnetGroup
    MultiAZ: false
    PubliclyAccessible: false
    StorageType: gp2
